cluster:
  enable: false
  instance_name: $instance_name
  etcd: http://$etcd_ip1:$etcd_port1,http://$etcd_ip2:$etcd_port2,http://$etcd_ip3:$etcd_port3

registered_frameworks:
  - lava
  - labgrid

frameworks_config:
  lava:
    identities: $lava_identity
    priority: 1
  labgrid:
    lg_crossbar: ws://$labgrid_crossbar_ip:20408/ws
    priority: 2
    seize: false

priority_scheduler: true

api_server:
  ip: $fc_server_ip
  port: 8600

managed_resources:
  $farm_type:
    $device_type:
      - $resource1
      - $resource2
