version: "3"

services:
  fc_server:
    build:
      context: ../..
      dockerfile: docker/fc_server/Dockerfile
    image: fc_server
    container_name: fc_server
    tty: true
    ports:
      - "8600:8600"
    volumes:
      - $PWD/../../fc_server/config/lavacli.yaml:/root/.config/lavacli.yaml
      - $PWD/../../fc_server/config/:/fc/fc_server/config/
      - /etc/localtime:/etc/localtime
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
